// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5FFxGeDSrF0EdkQGQtpe0p287Le5_jPE',
    appId: '1:790061742575:web:8b5c10e7ff8c8c98821e1a',
    messagingSenderId: '790061742575',
    projectId: 'smart-wear-app',
    authDomain: 'smart-wear-app.firebaseapp.com',
    storageBucket: 'smart-wear-app.appspot.com',
    measurementId: 'G-M7NXPP982G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlfflhmUnJfvfQap1C7FvX50cMrwul9QM',
    appId: '1:790061742575:android:ac06e57250bc3975821e1a',
    messagingSenderId: '790061742575',
    projectId: 'smart-wear-app',
    storageBucket: 'smart-wear-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZBDLqA_jYrBFvDKwGiekgpeTr4ackg4g',
    appId: '1:790061742575:ios:a9bb3511a8634f25821e1a',
    messagingSenderId: '790061742575',
    projectId: 'smart-wear-app',
    storageBucket: 'smart-wear-app.appspot.com',
    iosClientId: '790061742575-mivhi24dbftu473uvrn92iddgh1fq03p.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartWearApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZBDLqA_jYrBFvDKwGiekgpeTr4ackg4g',
    appId: '1:790061742575:ios:a9bb3511a8634f25821e1a',
    messagingSenderId: '790061742575',
    projectId: 'smart-wear-app',
    storageBucket: 'smart-wear-app.appspot.com',
    iosClientId: '790061742575-mivhi24dbftu473uvrn92iddgh1fq03p.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartWearApp',
  );
}
